### ISSUE TITLE
リリース申請

### ISSUE THREAD

**Issue by obaya884** [obaya884/CharmMe#44]
## Task List
- [x] パッケージ名変更
- [x] アプリ名変更
- [x] アイコン作成(512px * 512px)
- [x] アイコン変更
- [x] ストア用スクリーンショット(2枚〜)
- [x] 高解像度アイコン(32bit png, 512px*512px, 1024kb)
- [x] 宣伝用画像(1024px * 500px)
- [x] 署名済みAPK作成
- [x] タイトル(30文字)
- [x] 簡単な説明(80文字)
- [x] 詳細な説明(4000文字)
- [x] APKファイルのアップロード
- [x] 申請
